micronaut:
  application:
    name: micronautEventProcessor
netty:
  default:
    allocator:
      max-order: 3
app:
  event:
    groupId: product-stream-group-01
    topic: product-stream
    dead-letter: "product-stream-dead-letter"
    should-dead-letter-unhandled: true
  error:
    topic: event-processor-error