micronaut:
  application:
    name: micronautEventProcessor
netty:
  default:
    allocator:
      max-order: 3
#kafka:
#  bootstrap:
#    servers: 'localhost:9092'

product:
  stream:
    topic: product-stream
    groupId: product-stream-group-01

app:
  event:
    dead-letter: "product-stream-dead-letter"
    should-dead-letter-unhandled: true
  error:
    topic: event-processor-error