/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.slf4j:slf4j-api:1.7.36")
        implementation("org.slf4j:slf4j-simple:1.7.36")

    }

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.0")
}

tasks.test {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
